### ISSUE TITLE
Hactoberfest

### ISSUE THREAD

**Issue by Nivedita-Samanta** [Nivedita-Samanta/leap-year#1]
This repo is created with Hactoberfest in mind.

**Comment by Shreyas-SAS** [comment]
what exactly are these multiple repositories for?

**Comment by Shreyas-SAS** [comment]
you know right self accepting of PR can lead to disqualification? also its not ethical for you to take someones deserved swags by such malpractices.

**Comment by Nivedita-Samanta** [comment]
This are made for practice sessions of my college juniors so that they get an idea of how hactoberfest works before it starts.
Don't worry about the malpractices. I was making this repo for a live demo.

**Comment by Shreyas-SAS** [comment]
Yeah no worries. Have seen people do this kind of stuff thus thought its good to warn people once. It was 4 different repos that I stumbled upon so it was a bit sus too. 
Good to hear though.

**Comment by Nivedita-Samanta** [comment]
Actually we were organising bootcamps in our college on behalf of Google Developer Student Club.
They were taught how to use Git and GitHub and open source contribution.
And finally how the Hactoberfest works.
So we had to make this new acc and show them how the repo functions.
Hope u understand.

**Comment by Shreyas-SAS** [comment]
Yeah got it the moment you mentioned juniors. I have personally taken a session on github a few months back as MLSA so can understand. Please do not worry about it. Just making sure that the development world is still a bit ethical. Peace.

**Comment by Shreyas-SAS** [comment]
Best of luck for future endeavors.

**Comment by Nivedita-Samanta** [comment]
Thank u
